# Fusion of ratings and movies

In [18]:
import pandas as pd
# we import the processed dataframes
movies_df_mb = pd.read_parquet('../data/processed/movies_df.parquet')
ratings_df = df = pd.read_parquet('../data/processed/ratings_df.parquet')

#we merge the ratings and movies dataframes on 'movieId' 
# to create a combined dataframe
#merge is done with a left join to keep all ratings, 
# even if some movies could be missing in the movies dataframe
ratings_movies_df = ratings_df.merge(movies_df_mb, on='movieId', how='left')

In [19]:
# we check the structure of the merged dataframe 
# and the number of missing values in it
print("structure of ratings_df and of ratings_movies_df:", ratings_df.shape, ratings_movies_df.shape)          # même nombre de lignes
print("number of missing values in columns of ratings_movies_df:", ratings_movies_df.isna().sum())    
print("total number of missing values in ratings_movies_df:", ratings_movies_df.isna().sum().sum()) 
display(ratings_movies_df.head(5))

structure of ratings_df and of ratings_movies_df: (2000000, 5) (2000000, 28)
number of missing values in columns of ratings_movies_df: userId                 0
movieId                0
rating                 0
timestamp              0
year_of_rating         0
title                  0
genres                 0
year_of_release       37
(no genres listed)     0
Action                 0
Adventure              0
Animation              0
Children               0
Comedy                 0
Crime                  0
Documentary            0
Drama                  0
Fantasy                0
Film-Noir              0
Horror                 0
IMAX                   0
Musical                0
Mystery                0
Romance                0
Sci-Fi                 0
Thriller               0
War                    0
Western                0
dtype: int64
total number of missing values in ratings_movies_df: 37

,userId,movieId,rating,timestamp,year_of_rating,title,genres,year_of_release,(no genres listed),Action,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,2,3.5,2005-04-02 23:53:47,2005,Jumanji (1995),Adventure|Children|Fantasy,1995,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,29,3.5,2005-04-02 23:31:16,2005,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi,1995,0,0,...,0,0,0,0,1,0,1,0,0,0
2,1,32,3.5,2005-04-02 23:33:39,2005,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller,1995,0,0,...,0,0,0,0,1,0,1,1,0,0
3,1,47,3.5,2005-04-02 23:32:07,2005,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1995,0,0,...,0,0,0,0,1,0,0,1,0,0
4,1,50,3.5,2005-04-02 23:29:40,2005,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1995,0,0,...,0,0,0,0,1,0,0,1,0,0

# Fusion of genome_scores and genome_tags

In [20]:
# we import the genome scores and genome tags dataframes
genome_scores_df = pd.read_parquet('../data/processed/genome_scores_df.parquet')
genome_tags_df = pd.read_parquet('../data/processed/genome_tags_df.parquet')

#we merge the genome scores and genome tags dataframes on 'tagId'
#with a left join to keep all genome scores, 
# even if some tags could be missing in the genome tags dataframe
genome_merge_df = genome_scores_df.merge(genome_tags_df, on="tagId", how="left")
display(genome_merge_df.head(10))
print("number of missing values:", genome_merge_df.isnull().sum().sum())

   movieId  tagId  relevance           tag
0        1      1    0.02500           007
1        1      2    0.02500  007 (series)
2        1      3    0.05775  18th century
3        1      4    0.09675         1920s
4        1      5    0.14675         1930s
5        1      6    0.21700         1950s
6        1      7    0.06700         1960s
7        1      8    0.26275         1970s
8        1      9    0.26200         1980s
9        1     10    0.03200  19th century

number of missing values: 0

# Pivot of genome to movies_profile

In [21]:
# we inversed the merged dataframe genome_merge_df 
# to have one line per movie and one column per tag, 
# with the relevance as values
movies_profile_df = genome_merge_df.pivot(index="movieId",columns = "tag",values = "relevance")
print("number of columns in movies_profile_df:", movies_profile_df.shape[1])
# below, we found the same number of movies in movies_profile_df 
# as in genome_scores_df and no missing values.
#  Merge and pivot operations went well
print("number of lines in movies_profile_df:", movies_profile_df.shape[0])
print("number of missing values in movies_profile_df:", movies_profile_df.isnull().sum().sum())
display(movies_profile_df.head(5))

number of columns in movies_profile_df: 1128
number of lines in movies_profile_df: 10381
number of missing values in movies_profile_df: 0

tag,007,007 (series),18th century,1920s,1930s,1950s,1960s,1970s,1980s,19th century,...,world politics,world war i,world war ii,writer's life,writers,writing,wuxia,wwii,zombie,zombies
movieId,,,,,,,,,,,,,,,,,,,,,
1,0.02500,0.02500,0.05775,0.09675,0.14675,0.21700,0.06700,0.26275,0.26200,0.03200,...,0.03950,0.01800,0.04575,0.03275,0.12500,0.04150,0.01925,0.03625,0.07775,0.02300
2,0.03975,0.04375,0.03775,0.04800,0.11025,0.07250,0.04775,0.10975,0.09925,0.02050,...,0.04175,0.01925,0.01725,0.02425,0.12550,0.02250,0.01550,0.01475,0.09025,0.01875
3,0.04350,0.05475,0.02800,0.07700,0.05400,0.06850,0.05600,0.18500,0.04925,0.02675,...,0.04150,0.02675,0.02775,0.03425,0.15550,0.03675,0.01700,0.01950,0.09700,0.01850
4,0.03725,0.03950,0.03675,0.03100,0.06825,0.04050,0.02325,0.08700,0.05125,0.03025,...,0.05750,0.03375,0.02275,0.03975,0.18525,0.05925,0.01500,0.01525,0.06450,0.01300
5,0.04200,0.05275,0.05925,0.03675,0.07525,0.12525,0.02850,0.08500,0.02950,0.02875,...,0.04250,0.02825,0.02150,0.02600,0.14275,0.02075,0.01650,0.01675,0.10750,0.01825

# Mapping of movies between ratings_movies_df and movies_profile

In [22]:
#even if merge of ratings_movies_df and movies_profile_df could not be done,
#  we can check if all movies of ratings_movies_df are present in movies_profile_df
to_look = set(ratings_movies_df['movieId'])
found = set()
found = to_look & set(movies_profile_df.index)
missing =to_look-found
print("number of movies of ratings_movies_df missing in movies_profile_df: ", len(missing))
# we have 6426 movies of ratings_movies_df missing in movies_profile_df

number of movies of ratings_movies_df missing in movies_profile_df:  6426

# Fusion between ratings_movies_df and movies_profile_df

In [23]:
# we wanted to merge the ratings_movies_df and movies_profile_df dataframes 
# on 'movieId' to have a combined dataframe with all ratings and all tags for each movie.
# Unfortunately, below, the two lines of code (in dash lines) could not be executed because
#they exhausted the memory of my computer: 
# the kernel ran out of memory and crashed.
# (peak at 17 GB RAM while my computer has 8 GB RAM) 
#movies_ratings_profile_df = ratings_movies_df.merge(movies_profile_df, on="movieId", how="left")
#display(movies_ratings_profile_df.head(5))

# therefore, let's try to do a merge with a new movies_profile_reduc_df 
# which will have only the 270 tags with the largest variances, instead of all 1128 tags.
# we constructed this dataframe in the notebook genome_scores_data_exploration.ipynb.
# let's import it and redo the pivot and the merge to see if kernell can handle it.

# Fusion of genome_scores_reduc_df and genome_tags_df

In [24]:
# we need to import only the genome_scores_reduc_df dataframe
genome_scores_reduc_df = pd.read_parquet('../data/processed/genome_scores_reduc_df.parquet')


#we merge the genome_scores_reduc_df and genome_tags_df dataframes on 'tagId'
#with a left join to keep all genome_scores_reduc_df, 
# even if some tags could be missing in the genome tags dataframe
genome_merge_reduc_df = genome_scores_reduc_df.merge(genome_tags_df, on="tagId", how="left")
display(genome_merge_reduc_df.head(10))
print("number of missing values:", genome_merge_reduc_df.isnull().sum().sum())

   movieId  tagId  relevance                tag
0        1     13    0.18800                80s
1        1     18    0.11050             absurd
2        1     19    0.67050             action
3        1     20    0.18450      action packed
4        1     22    0.28250  adapted from:book
5        1     26    0.08100        adolescence
6        1     29    0.89200          adventure
7        1     30    0.67625       affectionate
8        1     46    0.25575           allegory
9        1     62    0.68775            animals

number of missing values: 0

# Pivot of genome_scores_reduc_df

In [25]:
# we inversed the merged dataframe genome_merge_reduc_df 
# to have one line per movie and one column per tag, 
# with the relevance as values
movies_profile_reduc_df = genome_merge_reduc_df.pivot(index="movieId",columns = "tag",values = "relevance")

# below, we found the same number of movies in movies_profile_reduc_df 
# as in genome_scores_reduc_df and no missing values.
#  Merge and pivot operations went well
print("number of columns in movies_profile_reduc_df:", movies_profile_reduc_df.shape[1])
print("number of lines in movies_profile_reduc_df:", movies_profile_reduc_df.shape[0])
print("number of missing values in movies_profile_reduc_df:", movies_profile_reduc_df.isnull().sum().sum())
display(movies_profile_reduc_df.head(5))

number of columns in movies_profile_reduc_df: 270
number of lines in movies_profile_reduc_df: 10381
number of missing values in movies_profile_reduc_df: 0

tag,80s,absurd,action,action packed,adapted from:book,adolescence,adventure,affectionate,allegory,animals,...,visual,visually appealing,visually stunning,war,wartime,weapons,weird,witty,women,world war ii
movieId,,,,,,,,,,,,,,,,,,,,,
1,0.18800,0.11050,0.67050,0.18450,0.28250,0.08100,0.89200,0.67625,0.25575,0.68775,...,0.60425,0.41050,0.44500,0.06250,0.10075,0.25850,0.29925,0.77675,0.11275,0.04575
2,0.22575,0.18975,0.64600,0.40025,0.60200,0.14350,0.98100,0.10550,0.24300,0.91450,...,0.32475,0.19125,0.32550,0.04125,0.04750,0.15700,0.31600,0.18000,0.14750,0.01725
3,0.09050,0.10400,0.16475,0.17375,0.20775,0.08375,0.41200,0.09525,0.15750,0.09175,...,0.11400,0.21250,0.16575,0.03825,0.07225,0.13875,0.16800,0.19950,0.37075,0.02775
4,0.11750,0.16875,0.13950,0.12900,0.44650,0.06175,0.13800,0.10575,0.08050,0.13075,...,0.12250,0.18575,0.18000,0.03625,0.05800,0.31475,0.17850,0.10725,0.97675,0.02275
5,0.07175,0.16100,0.16350,0.22650,0.21075,0.05100,0.15375,0.12225,0.09575,0.14975,...,0.14700,0.18750,0.22100,0.03550,0.06625,0.13150,0.26975,0.12000,0.48900,0.02150

# Fusion between ratings_movies_df and movies_profile_reduc_df

In [26]:
# initially we wanted to merge the ratings_movies_df and movies_profile_df dataframes 
# on 'movieId' to have a combined dataframe with all ratings and all tags for each movie.
# Unfortunately, below, the two lines of code (in dash lines) could not be executed because
#they exhausted the memory of my computer: 
# the kernel ran out of memory and crashed.
# (peak at 17 GB RAM while my computer has 8 GB RAM) 
#movies_ratings_profile_df = ratings_movies_df.merge(movies_profile_df, on="movieId", how="left")
#display(movies_ratings_profile_df.head(5))

# but now, let's try to merge the ratings_movies_df and movies_profile_reduc_df dataframes.
# Maybe, since we devided the number of columns of movies_profile_df by 4 (from 1128 to 270 in movies_profile_reduc_df), 
# the kernel will be able to handle it.

movies_ratings_profile_df = ratings_movies_df.merge(movies_profile_reduc_df, on="movieId", how="left")
display(movies_ratings_profile_df.head(5))

,userId,movieId,rating,timestamp,year_of_rating,title,genres,year_of_release,(no genres listed),Action,...,visual,visually appealing,visually stunning,war,wartime,weapons,weird,witty,women,world war ii
0,1,2,3.5,2005-04-02 23:53:47,2005,Jumanji (1995),Adventure|Children|Fantasy,1995,0,0,...,0.32475,0.19125,0.32550,0.04125,0.04750,0.15700,0.31600,0.18000,0.14750,0.01725
1,1,29,3.5,2005-04-02 23:31:16,2005,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi,1995,0,0,...,0.99425,0.95775,0.99500,0.02500,0.14050,0.18800,0.98175,0.34300,0.12125,0.02875
2,1,32,3.5,2005-04-02 23:33:39,2005,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller,1995,0,0,...,0.82500,0.80375,0.81700,0.01975,0.07800,0.38000,0.87650,0.39375,0.07875,0.01275
3,1,47,3.5,2005-04-02 23:32:07,2005,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1995,0,0,...,0.74575,0.62625,0.58875,0.03825,0.10425,0.24225,0.70275,0.44375,0.15675,0.02075
4,1,50,3.5,2005-04-02 23:29:40,2005,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1995,0,0,...,0.62275,0.74425,0.61275,0.09150,0.17550,0.37525,0.70850,0.69950,0.09100,0.06300